swagger: 2
info:
  version: 0.0.1
  title: Twitter search example
  description: Twitter search example
  termsOfService: "http://apigee.com/about/terms"
  contact:
    name: Apigee 127
    url: "https://github.com/apigee-127"
  license:
    name: MIT
    url: "http://opensource.org/licenses/MIT"
host: localhost
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
x-a127-config:
  apigeeProxyKey: &apigeeProxyKey CONFIGURED
  apigeeProxyUri: &apigeeProxyUri CONFIGURED
x-volos-resources:
  cache:
    provider: volos-cache-memory
    options:
      name: name
      ttl: 10000
  quota:
    provider: volos-quota-memory
    options:
      timeUnit: minute
      interval: 1
      allow: 2
  oauth2:
    provider: volos-oauth-apigee
    options:
      key: *apigeeProxyKey
      uri: *apigeeProxyUri
    validGrantTypes:
      - client_credentials
      - authorization_code
      - implicit_grant
      - password
    passwordCheck: passwordCheck
    paths:
      note: these will be placed in the paths section
      authorize: /authorize
      token: /accessToken
      invalidate: /invalidate
      refresh: /refresh
paths:
  /twitter:
    x-swagger-router-controller: twitter
    x-volos-authorizations:
      oauth2: {}
    x-volos-apply:
      cache: {}
      quota: {}
    get:
      description: Returns the results of a search of Twitter
      summary: Returns the results of a search of Twitter
      operationId: search
      produces:
        - application/json
      parameters:
        - name: search
          in: query
          description: The Query to pass to Twitter
          required: true
          type: string
      responses:
        "200":
          description: Twitter search response
          schema:
            $ref: "#/definitions/TwitterSearchResponse"
        default:
          description: Error payload
          schema:
            $ref: "#/definitions/ErrorModel"
  /twitter2:
    get:
      description: Returns the results of a search of Twitter
      summary: Returns the results of a search of Twitter
      operationId: search
      produces:
        - application/json
      parameters:
        - name: search
          in: query
          description: The Query to pass to Twitter
          required: true
          type: string
      responses:
        "200":
          description: Twitter search response
          schema:
            $ref: "#/definitions/TwitterSearchResponse"
        default:
          description: Error payload
          schema:
            $ref: "#/definitions/ErrorModel"
definitions:
  TwitterSearchResponse:
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string
  ErrorModel:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
